# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pralhad's Blog
email: https://github.com/Pralhad-Deshpande
description: >- # this means to ignore newlines until "baseurl:"
 This blog documents the wonderful concepts that I have leared as I explore my interest in crypto-economics. Although technical concepts such as authenticated BFT and privacy will be discussed at great length, this is by no means a purely technical blog. Blog posts may take a historical perspective and dive into the evolution of money and explore how crypto-economics fits into that space. Blog posts may also study popular present day payment systems and explore the arguments for central bank issued digital currencies. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: pralhad
github_username:  Pralhad-Deshpande

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
